### ISSUE TITLE
Support Bazel workspaces that have a soft linked WORKSPACE file

### ISSUE THREAD

**Issue by asmittal** [salesforce/bazel-eclipse#164]
In our code setup, Workspace file in the git root is actually soft link to the actual file, which is nested bit deeper. 
On Importing the softlink workspace file, window to select the projects/modules is not shown. It imports the workspace file, showing empty workspace project. 
OS: Mac latest
Eclipse : Sept 2020
Plugin: Latest

**Comment by plaird** [comment]
@asmittal what would really help with this feature request is an explanation of why your repo has the WORKSPACE file soft linked from a different directory. Also, does the soft linked WORKSPACE have load() statements for other .bzl files that are also soft linked?

**Comment by plaird** [comment]
@asmittal  this feature went in as of PR #175 and it will appear in a release shortly. Please try it out when you can. Because of the way the system File Open dialog works, the solution wasn't nice. So I can't guarantee this feature will stay in forever if it causes problems.

I have asked a few times, can you please explain why you are soft linking your WORKSPACE file? I am trying to understand the reason as I have not seen that before. That will help justifying keeping this feature. Thanks!

**Comment by plaird** [comment]
@asmittal  BEF 1.2.3 has now been released with your feature.

**Comment by asmittal** [comment]
> @asmittal this feature went in as of PR #175 and it will appear in a release shortly. Please try it out when you can. Because of the way the system File Open dialog works, the solution wasn't nice. So I can't guarantee this feature will stay in forever if it causes problems.
> 
> I have asked a few times, can you please explain why you are soft linking your WORKSPACE file? I am trying to understand the reason as I have not seen that before. That will help justifying keeping this feature. Thanks!

Really sorry, for responding late on this. I tried to check with our build team for having this complicated structure. But even after days haven't received any response. 
In case I do hear from them in coming days, I will let you know.
