### ISSUE TITLE
Turn 'bazel-eclipse' into a mono repo hosting the SDK and the Bazel Language Server

### ISSUE THREAD

**Issue by guw** [salesforce/bazel-eclipse#237]
I think splitting out the SDK into a separate Git repo is correct from functional/architectural/modularization perspective. 

However, I find that SDK evolution (currently) is very coupled to Bazel Eclipse. For example, a recent look at Bazel Eclipse commit history is this:
![image](https://user-images.githubusercontent.com/191472/121854608-ae19a400-ccf2-11eb-9fbf-c24363efaba1.png)

It becomes difficult to keep track/context of changes and their motivation. A multi-repository setup complicates things.

We also would like to make the Bazel Language Server share code with BEF again. I believe it would be great if we can have a single repository and tweak the CI pipeline to automatically build/run tests when core components shared by Bazel Eclipse and Bazel Language Server change.

My proposal is to turn this repo into a mono-repo for all three components and produce them out of this repo. If at a later point flexibility is really needed we can still move the SDK back into its own repo.

**Comment by plaird** [comment]
Gunnar and I discussed this, and we will have the SDK in both the IDE repo and the SDK repo...

We do need a copy of the SDK to be in the IDE repo, because it would be really unproductive if it wasn't. Most IDE work entails updates to the SDK. To have to cut new releases of the SDK, or git submodule the SDK into the IDE repo, is not that appealing. 

And it is my personal goal to promote the SDK as a standalone module that other developers use in other projects. It is hard to do if embedded in the IDE repo because GitHub project management tools (Issues, Releases, Projects) are repo-scoped. Finding the latest release of the SDK, or searching for an Issue, amongst entries related to BEF and LS would be annoying.

So we will maintain a mirrored copy of the SDK in both repos. I have signed up to manage the mirroring. I have some lightweight copy scripts (./sdk_copybara.sh, ./sdk_copybara_reverse.sh) that I am using for now to transfer updates between the repos. Once the LS moves in, and we refactor the repo layout for that, I will look into a stronger solution like copybara.

**Comment by plaird** [comment]
Reopening to track the actual merge of this idea.

**Comment by plaird** [comment]
Doc re-org to allow BEF and BJLS to coexist was done as #295.

**Comment by plaird** [comment]
CI now has support for both products. There are BEF jobs and BJLS jobs. What we still need to figure out is how to exclude the other feature when writing the update-site. So when we release BEF we don't also release the BJLS.

**Comment by plaird** [comment]
@PMitrafanau @AlexeiShmidman I have revised the GitHub Action workflows to support BJLS. The workflows produce Eclipse update sites (one for release candidates, one for official releases). You can of course modify the workflows to release things differently. Please be careful not to deploy anything into the existing BEF update sites, thanks!

https://github.com/salesforce/bazel-eclipse/tree/gh-pages/bjls

With that, I will close this issue as done.
