### ISSUE TITLE
BEF does not populate Eclipse Problems View with warnings

### ISSUE THREAD

**Issue by plaird** [salesforce/bazel-eclipse#33]
As a BEF user
I would like JDT warnings to appear in the Eclipse Problems View
Such that I am not surprise when I open a file in the Java editor and see warnings

**Background:**
Currently, the Problems View is populated by errors scraped from the Bazel command line build of the packages. But this loses the warnings that JDT generates.

**Comment by simontoens** [comment]
I am able to access the problems through JavaProject.getPackageFragments().getCompilationUnits().reconcile(...).  Not 100% sure that is the right way to go, since it seems to re-create an AST, whereas I really just want to use whatever JDT has already computed, but I don't see any other way right now.  I will at least try to make some progress here.

**Comment by simontoens** [comment]
Ok, some slow progress here, but better than nothing.  I figured out I can register a listener to get access to the existing AST: 
```
JavaCore.addElementChangedListener(...)
```
Then in the impl:
```
public void elementChanged(ElementChangedEvent e) {
            CompilationUnit ast = e.getDelta().getCompilationUnitAST();
            for (IProblem problem : ast.getProblems()) {
            }
        }
```
