### ISSUE TITLE
Unresolved compilation problem: The constructor JSONTokener(FileInputStream) is undefined

### ISSUE THREAD

**Issue by invader35** [salesforce/bazel-eclipse#54]
When importing a project the import throws the following message:

Unresolved compilation problem: 
  The constructor JSONTokener(FileInputStream) is undefined

The eclipse log file is not showing any errors and the bazel command executed is also finishing successfully. (also when tried on the command line)

**Comment by plaird** [comment]
Thanks for the report. Is that _during_ import in a popup dialog, or an error shown _after_ import in the Problems View?

**Comment by plaird** [comment]
The likely source of this is this class from this line in the BEF:
https://github.com/salesforce/bazel-eclipse/blob/master/plugin-libs/plugin-model/src/main/java/com/salesforce/bazel/eclipse/model/AspectPackageInfo.java#L145

Which references this constructor:
https://github.com/stleary/JSON-java/blob/master/JSONTokener.java#L83
which has been in the library since the very first commit to the project. So this is a strange problem.

But I see that the BEF model plugin is importing the _org.json_ package without specifying a version in OSGi, which is a bad practice:
https://github.com/salesforce/bazel-eclipse/blob/master/plugin-libs/plugin-model/META-INF/MANIFEST.MF#L12

I will update the manifest to import the specific version of _org.json_ that we bundle with the feature. It would be nice to know where that odd version _org.json.JSONTokener_ is coming from, but it probably isn't worth tracking down. We should have set a version on our import to avoid this problem in any case.

**Comment by invader35** [comment]
Thanks for fixing this so quickly

**Comment by plaird** [comment]
Thanks for reporting! I didn't mention it explicitly, but this fix did get built and released as 1.0.3:

https://github.com/salesforce/bazel-eclipse/releases/tag/1.0.3
